In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'2.4.0+cu121'

In [4]:
arr=np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr.dtype

dtype('int64')

In [10]:
type(arr)

numpy.ndarray

**Converting an array to a torch tensor:**

In [11]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5])

In [12]:
x=torch.from_numpy(arr)

In [13]:
x

tensor([1, 2, 3, 4, 5])

The other way is using as_tensor function

In [14]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [15]:
x.dtype

torch.int64

In [18]:
arr2d=np.arange(0,12)
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
arr2d.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [23]:
x2=arr2d.reshape(2,6)

In [24]:
x2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
arr2d[0]=9999
arr2d

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [27]:
x2

array([[9999,    1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11]])

**Note**

As is clear when we change the arr elements the tensor elements are also changed. Thus the risen question  is that how we can remove this connection?

In [29]:
my_arr=np.arange(0,10)
my_tensor=torch.tensor(my_arr)
my_other_tensor=torch.from_numpy(my_arr)

In [30]:
my_arr[0]=89898

In [31]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
my_other_tensor

tensor([89898,     1,     2,     3,     4,     5,     6,     7,     8,     9])

Note: As is clear torch.tensor would save a copy of the array.

Note torch.Tensor would generate the float form of the arrays instead of the int

In [35]:
d=np.arange(0,10)
f=torch.tensor(d)
f.dtype

torch.int64

In [36]:
g=torch.Tensor(d)
g.dtype

torch.float32

Note: We have some functions in torch to make placeholders

torch.empty() would make a tensor with elements near to zero

In [37]:
torch.empty(2,2)

tensor([[0.0000e+00, 0.0000e+00],
        [1.2612e-44, 0.0000e+00]])

torch.zeros() would make a tensor with zero elements

In [38]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [40]:
torch.arange(0,13,2)

tensor([ 0,  2,  4,  6,  8, 10, 12])

In [43]:
torch.arange(0,12,2).reshape(2,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10]])

In [46]:
torch.linspace(0,14,18)
#returns lineary space

tensor([ 0.0000,  0.8235,  1.6471,  2.4706,  3.2941,  4.1176,  4.9412,  5.7647,
         6.5882,  7.4118,  8.2353,  9.0588,  9.8824, 10.7059, 11.5294, 12.3529,
        13.1765, 14.0000])

Note: you can also make tensor from skract and with out converting array to tensor.

In [47]:
torch.tensor([1,2,34])

tensor([ 1,  2, 34])

Note: You can change the data type in the tensor

In [48]:
my_tensor=torch.tensor([1,2,4])

In [49]:
my_tensor.dtype

torch.int64

In [50]:
my_tensor=my_tensor.type(torch.int32)

In [51]:
my_tensor.dtype

torch.int32

**Making Randoms in Tensor**

In [52]:
torch.rand(4,3)

tensor([[0.5388, 0.9872, 0.8161],
        [0.0861, 0.2681, 0.0070],
        [0.6062, 0.2844, 0.0192],
        [0.6035, 0.6476, 0.3976]])

Randn would make normal distribution

In [53]:
torch.randn(3,4)

tensor([[-0.2638,  1.3503, -1.2502, -1.4412],
        [ 1.5116,  1.0697,  0.3868,  0.6131],
        [ 0.4098,  0.8361, -0.1820, -0.4181]])

In [54]:
torch.randint(low=0, high=6, size=(3,7))

tensor([[0, 1, 1, 2, 4, 5, 5],
        [0, 3, 1, 2, 5, 0, 3],
        [2, 4, 3, 3, 2, 2, 2]])

Note: you can also make rand tensors with the shape of another tensor

In [57]:
x=torch.zeros(3,4)

In [58]:
torch.rand_like(x)

tensor([[0.4331, 0.1757, 0.3021, 0.8683],
        [0.1084, 0.7305, 0.5589, 0.5587],
        [0.0743, 0.0104, 0.5763, 0.1550]])


For having the reproducabilities of the random tensors you can use seeds!!

In [59]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [73]:
arr=np.arange(0,4)
arr

array([0, 1, 2, 3])

In [74]:
arr2=np.array([1,2,3,4])
arr2

array([1, 2, 3, 4])

In [75]:
arr2+arr

array([1, 3, 5, 7])

In [76]:
arr2*arr

array([ 0,  2,  6, 12])

In [77]:
a=[1,3,4]
b=[4,5,6]
a+b

[1, 3, 4, 4, 5, 6]

**Multiplying**

In [78]:
a=torch.arange(10).reshape(2,5)
a

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [79]:
b=torch.randint(0,10,(2,5))
b

tensor([[5, 5, 7, 6, 9],
        [6, 3, 1, 9, 3]])

In [80]:
a+b

tensor([[ 5,  6,  9,  9, 13],
        [11,  9,  8, 17, 12]])

In [81]:
a*b

tensor([[ 0,  5, 14, 18, 36],
        [30, 18,  7, 72, 27]])

In [82]:
a.mul(b)

tensor([[ 0,  5, 14, 18, 36],
        [30, 18,  7, 72, 27]])

In [83]:
a

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Note: if we use mul_ the tensor would save on a

In [84]:
a.mul_(b)

tensor([[ 0,  5, 14, 18, 36],
        [30, 18,  7, 72, 27]])

In [85]:
a

tensor([[ 0,  5, 14, 18, 36],
        [30, 18,  7, 72, 27]])

This is the same on other opperations like add_

Note: A*b is always element by element product. for matrix multiply we can use the following function

In [87]:
a=torch.tensor([[0,2,3],[3,4,5]])
a

tensor([[0, 2, 3],
        [3, 4, 5]])

In [89]:
b=torch.tensor([[6,7],[8,9],[5,6]])

In [90]:
a.shape

torch.Size([2, 3])

In [91]:
b.shape

torch.Size([3, 2])

In [92]:
torch.mm(a,b)

tensor([[31, 36],
        [75, 87]])

numel() would retrun the number of the elements in a tensor

In [93]:
b.numel()

6

In [95]:
len(b)
#number of rows

3